version: '3.9'
services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - postgres
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - resume-builder:/data/postgres

networks:
  postgres:
    driver: bridge
volumes:
  resume-builder: